import { useState } from 'react'
import { movieApi } from '../lib/api'
import type { Profile } from '../types'
import type { AuthUser } from '../auth/authApi'

const genres = ['Action', 'Adventure', 'Comedy', 'Drama', 'Horror', 'Sci-Fi', 'Fantasy', 'Romance', 'Thriller', 'Mystery', 'Crime']

export default function ProfilePage({ profile, user, onSaved }: { profile: Profile; user: AuthUser; onSaved: () => void }) {
  const [selected, setSelected] = useState(profile.preferred_genres)
  const [saving, setSaving] = useState(false)
  const save = async () => { setSaving(true); try { await movieApi.updatePreferences(selected); onSaved() } finally { setSaving(false) } }
  return <section className="grid gap-5 rounded-[20px] border border-white/10 bg-[#121926]/85 p-6 shadow-xl shadow-black/15 sm:p-7"><div className="flex items-center gap-4"><div className="grid h-[58px] w-[58px] shrink-0 place-items-center rounded-[18px] bg-gradient-to-br from-[#8066ff] to-[#16c8ee] font-bold uppercase text-white shadow-lg shadow-cyan-500/20">{user.username.slice(0, 2)}</div><div><div className="text-[.7rem] font-bold tracking-[.14em] text-[#cad3ee]">{user.is_demo ? 'DEMO PROFILE' : 'VIEWER PROFILE'}</div><h3 className="mt-1.5 font-['Space_Grotesk'] text-xl font-semibold text-white">{user.username}</h3><p className="text-sm text-[#aebbd7]">{user.email}</p></div></div><div className="grid gap-3 rounded-2xl border border-white/[.08] bg-white/[.03] p-4 sm:grid-cols-3"><div><span className="text-xs uppercase tracking-wider text-[#7081a8]">Username</span><strong className="mt-1 block text-sm text-white">{user.username}</strong></div><div><span className="text-xs uppercase tracking-wider text-[#7081a8]">Email</span><strong className="mt-1 block truncate text-sm text-white">{user.email}</strong></div><div><span className="text-xs uppercase tracking-wider text-[#7081a8]">Account</span><strong className="mt-1 block text-sm text-white">{user.is_demo ? 'Demo access' : 'Registered'}</strong></div></div><div><div className="mb-3 text-sm font-semibold text-white">Preferred genres</div><div className="flex flex-wrap gap-2">{genres.map((genre) => <button className={`rounded-full border px-3.5 py-2 text-sm transition ${selected.includes(genre) ? 'border-[#8066ff]/60 bg-[#8066ff]/30 text-white' : 'border-white/10 bg-white/[.04] text-[#aebbd7] hover:border-[#8066ff]/40'}`} key={genre} onClick={() => setSelected((current) => current.includes(genre) ? current.filter((item) => item !== genre) : [...current, genre])}>{genre}</button>)}</div></div><button className="w-fit rounded-[9px] bg-gradient-to-br from-[#8066ff] to-[#16c8ee] px-4 py-2.5 font-bold text-white transition hover:brightness-110" onClick={() => void save()} disabled={saving}>{saving ? 'Saving...' : 'Save preferences'} <span className="ml-2">→</span></button></section>
}
